ssh -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
  set -e

  cd ~

  # Clone repo if not already cloned
  if [ ! -d "sample-python-app/.git" ]; then
    git clone https://github.com/RakeshKanzariya2218/sample-python-app.git
  fi

  # Go to repo folder
  cd sample-python-app

  # Pull latest changes
  git pull origin main

  # Create virtual environment if it doesn't exist
  if [ ! -d "venv" ]; then
    python3 -m venv venv
  fi
  source venv/bin/activate

  # Install/update dependencies
  pip install --upgrade pip
  pip install -r requirements.txt

  # Kill any running instances of app.py
  pkill -f "python3 app.py" || true
  sleep 2

  # Run the app in background with nohup
  nohup python3 app.py > app.log 2>&1 &

  sleep 3
  tail -n 20 app.log
EOF
