name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Flask App via SSH
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519             ## add your secret with private key in git-repo secrets 
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts       ## add server ip as host on secrets  -- also your server inside the authorised key contain pub ssh key ehich inside the owner ubuntu 

    - name: Deploy to EC2 and restart Flask app
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/sample-python-app

          # Pull the latest changes
          git pull origin main

          # Activate or create virtual environment
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate

          # Install/update dependencies
          pip install --upgrade pip
          pip install -r requirements.txt

          # Kill any previous app instance (safely)
          pkill -f "python3 app.py" || true

          # Run the app in background
          nohup python3 app.py > app.log 2>&1 &
        EOF
